### ISSUE TITLE
legacy code has no transactional integrity

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#10]
### Description

The diagram of the legacy process shows clearly: If an error happens during FTP upload, the mail is handed over to a human, while already having been entered into the webapplication.

### Acceptance Criteria

- [ ] Common error situation up to and including FTP upload must be anticipated and handled
- [X] minimum unit of work shall be a QueueItem, not a MailMessage

### Subtasks

- [X] use Orchestrator Queue and Dispatcher *or* a in-process queue
- [X] sanitize subject to be fit for use as filename (at minimum remove forbidden characters)
- [X] Prior to any output implement validation as part of data processing

### Related Issues / Dependencies

- Related to: #1 
- Depends on: #13 

### Priority

- Priority: High

### Attachments / Additional Resources

- Attachments: none
