### ISSUE TITLE
Implement testcases

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#11]
### Description

The legacy code does not have any tests

### Acceptance Criteria

- [X] Implement unit tests for newly added workflows
- [X] Implement end-to-end tests
- [X] Execution from within UiPath Studio

### Subtasks

- [X] Setup testdata
- [X] determine need for mock data
- [X] Write testcases (checked with Workflow Analyzer)
- [X] cover InitAllSettings
- [X] cover main entrypoint(s)
- [X] #9 needs to be done for end-to-end tests with an in_ConfigFile argument being possible

### Related Issues / Dependencies

- Related to: #1 
- Depends on #9 

### Priority

- Priority: Medium

### Attachments / Additional Resources

- Attachments: none

**Comment by cprima** [comment]
Fixed with 2162e35f3b2bfec72d7d9db523aa2f4056e3b190
