### ISSUE TITLE
Showcase demo review

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#12]
### Description

The results of the refactoring shall be made measurable and presentable.

### Acceptance Criteria

- [X] For each latest major version, Workflow Analyzer results are available for presentation
- [ ] For each latest major version, review questions exist
- [X] A robust way to access the code of the projects is implemented

### Subtasks

- [X] Have a snapshot tool
- [X] Have refactored major version v2
- [X] Have refactored major version v3+
- [ ] Write demo review playbook
- [X] Perform Workflow Analyzer analysis
- [ ] Determine metrics beyond Workflow Analyzer results

### Related Issues / Dependencies

- Related to: -
- Depends on: #1 

### Priority

- Priority: Medium

### Attachments / Additional Resources

- Attachments: none

**Comment by cprima** [comment]
### Next steps

@karamfo : Please

- [ ] download the zipped snapshots from the link on Google Drive provided
- [ ] test if each project can be opened (in parallel?)
- [ ] check if the Workflow Analyzer can be executed
- [ ] ~note down the results, maybe here an a (editable) comment~
- [ ] tbd

**Comment by cprima** [comment]
## Workflow Analyzer

| Version | Error | Warning | Info |
|---------|-------|---------|------|
| Legacy  | 3     | 208     | 16   |
| V2      | 0     | 135     | 45   |
| V3      | 2     | 159     | 58   |
| V4      | 0     | 3       | 50   |
