### ISSUE TITLE
Consistent arguments

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#14]
### Acceptance Criteria

- [ ] Consistent use of TransactionItem and Config
- [ ] most workflows have output arguments about success and statistics 
- [ ] …

### Subtasks

- [ ] Define a common out argument signature
- [ ] Lowest units of work shall not access dictionary keys
- [ ] Subtask 3

### Related Issues / Dependencies

- Related to: #1 
- Depends on: # (Issue number)

### Priority

- Priority: 

### Attachments / Additional Resources

- Attachments:

**Comment by cprima** [comment]
blueprint for out_Result
`
out_Result = New Dictionary(Of String, Object)
out_Result("Count")
…
`

blueprint for out_Status
`
out_Status = New Dictionary(Of String, Object)
out_Status("Count")
out_Status("isSuccess")
`

![image](https://github.com/user-attachments/assets/2f421b45-8e9f-4a68-a9e9-b4f41ed1a89d)
