### ISSUE TITLE
Fix potentially invalid filenames

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#15]
### Description

The filenames for .eml and .zip files are based on the mail subject, which is prone to contain characters invalid on the filesystem.

### Acceptance Criteria

- [X] Sanitization of the mail subject
- [X] testcase with exhaustive testdata

### Subtasks

- [X] Research invalid characters
- [X] Implement detection of invalid characters
- [X] generate exhaustive testdata
- [ ] Implement isValid and BuildFilename
- [X] refactor existing code to use new functionality

### Related Issues / Dependencies

- Related to: #1
- Depends on: -

### Priority

- Priority: Medium

### Attachments / Additional Resources

- Attachments: none
