### ISSUE TITLE
Refactor InjectInProcessQueue to handle varying input Array(of Object)

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#19]
### Description

Currently an Array(Of Mailmessages) is hardcoded to be passed into InjectInProcessQueue, but the code shall handle Mailmessages or (complete) Files. Handling of rows in an xlsx file is optional.

### Acceptance Criteria

- [ ] InjectInProcessQueue.xaml takes a parameter to set the strategy
- [ ] at minimum the strategies "Files" and "MailMessages" are to be implemented
- [ ] 100% testcoverage

### Subtasks

- [ ] Use an Array(Of Object) with appropriate casts
- [ ] InjectInProcessQueue to use "polymorphism" (need to decide on a better term)
- [ ] Implement InjectInProcessQueueFiles
- [ ] Implement InjectInProcessQueueMaiMessages

### Related Issues / Dependencies

- Related to: #18 
- Depends on: none

### Priority

- Priority: Medium

### Attachments / Additional Resources

- Attachments: tbd
