### ISSUE TITLE
intermediate email folder "processing"

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#4]
### Description

Implement multi-step IMAP folder move operations

### Acceptance Criteria

- [ ] same mailmessage must move multiple times
- [ ] a folder processing holds the current mail being worked on
- [ ] more than one mail in folder processing moves all into handover2human

### Subtasks

- [ ] fetch repeatedly
- [ ] conditionally handle count of mails in processing
- [ ] out of scope for now: breaks if multiple robots used

### Related Issues / Dependencies

- Related to: none
- Depends on: none

### Priority

- Priority: Medium

### Attachments / Additional Resources

- Attachments: none
