### ISSUE TITLE
implement FTP secure upload

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#6]
### Description

files generated during processings shall be zipped and uploaded, in the style of IKS – Internes Kontrollsystem / Internal Control System

### Acceptance Criteria

- [ ] zip file generated
- [ ] zip file appropriately named
- [ ] zip file uploaded to FTP via a secure connection

### Subtasks

- [ ] obtain FTP credentials
- [ ] implement file naming
- [ ] implement upload

### Related Issues / Dependencies

- Related to: none
- Depends on: none

### Priority

- Priority: Low

### Attachments / Additional Resources

- Attachments: none
