### ISSUE TITLE
Improve data entry into web application

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#7]
### Description

The initial codebase does not automate rpachallenge in a way that conforms to industry expectations: Only 1 contact is entered. To properly automate exactly 10 contacts must be processed.

### Acceptance Criteria

- [x] rpachallenge started
- [x] rpachallenge outcome evaluated
- [x] start the challenge only if 10 contacts to process, else enter without start

### Subtasks

- [x] conditionally handle count of mails
- [x] implement rpachallenge start
- [x] implement rpachallenge result evaluation

### Related Issues / Dependencies

- Related to: #1 
- Depends on: none

### Priority

- Priority: Low

### Attachments / Additional Resources

- Attachments: none

**Comment by cprima** [comment]
Implemented in 8dc57add747790b0a3c889ab48671d28233eca1a

Result logged out, no other use of the data so far

> Parsed results: Success Rate: 0%, Completed Fields: 0, Total Fields: 70, Execution Time: 00:02:43, Success Rate (Decimal): 0
