### ISSUE TITLE
Implement Config file

### ISSUE THREAD

**Issue by cprima** [rpapub/PurposefulPromethium#9]
### Description

The legacy code does not use the Config file

### Acceptance Criteria

- [X] file read once, as per REFramework
- [X] one config file per environment, minimum Dev and Prod 
- [X] Config variable passed down into any workflow
- [X] config items evaluated at the point where needed

### Subtasks

- [X] find any arguments that were passed down which can be substituted
- [X] substitute with config items wherever possible
- [X] remove unused arguments

### Related Issues / Dependencies

- Related to: #1 

### Priority

- Priority: High

### Attachments / Additional Resources

- Attachments: none
